### ISSUE TITLE
Editor - Category sub folder support

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#108]
Support group like maps into sub-categories under a main group title.
https://www.romraider.com/forum/viewtopic.php?t=17649

**Comment by Pytrex** [comment]
Example Definition;

Note: Hardest part would be figuring out how to handle automatically filling in category/subcategory nodes if they already exist. Would have to make it check if both the category and the subcategory exist, if so, add table node to subcategory. If not, create category and subcategory node. The goal is to allow for multiple subcategories (with different categories) to retain the same subcategory name. So you could have a fueling category with a limiters subcategory, as well as an ignition timing category with a limiters subcategory. 

	<table type="2D" name="Cranking Advance Table" category="Cranking and Startup" subcategory="Ignition Timing" storagetype="uint8" sizex="8" endian="big" userlevel="3" >
		<scaling units="Degrees" expression="x" to_byte="x" format="0"/>
	<table type="X Axis" name="Coolant Temperature (Fahrenheit)" sizex="8">
			<data>-40</data>
			<data>-4</data>
			<data>32</data>
			<data>68</data>
			<data>104</data>
			<data>140</data>
			<data>176</data>
			<data>212</data>
	</table>
	<description>mTCRADV- CRADV table// Cranking Timing A</description>
	</table>
