### ISSUE TITLE
Editor - Issues with Copying and Pasting

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#110]
When attempting to copy over larger amounts of cells, sometimes it fails to copy/paste all of them. When copying an entire map or table, sometimes it will only paste 4-8 cells of data, even when using the copy table and paste commands within RomRaider. It can also completely fail to paste at all, resulting in the "Paste" option remaining highlighted. This issue occurs for both manually copying+pasting as well as using the copy and paste options. Like mentioned prior, this isn't what normally happens. But when it does happen, it seems to continue to occur no matter what you do. Possible that a computer reset fixes it when this happens? But not confirmed. 

![Screenshot 2021-05-12 212944](https://user-images.githubusercontent.com/13327710/118064545-365dff80-b369-11eb-88b2-d6055846b7f2.png)

**Comment by phish27134** [comment]
I usually have no problem copying from RR, pasting mostly works has a few bugs, but coping into spreadsheets no problem better than ECUflsh

**Comment by Pytrex** [comment]
> I usually have no problem copying from RR, pasting mostly works has a few bugs, but coping into spreadsheets no problem better than ECUflsh

Sometimes, attempting to copy the entire table will result in it only copying two rows or only a few cells at a time. (Confirmed with pasting into notepad)
