### ISSUE TITLE
Editor - Sometimes Forced to Hit "Set" in order to Set an Axis Value

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#117]
Sometimes (primarily with tables, rather than maps), certain tables won't let you enter new values into the axis. You can highlight the axis, but hitting enter won't update the values to whatever you want to set them to. But by hitting "set", it properly sets the value. This happens with scalings and raw values, so I don't think the scaling has any impact.

**Comment by dschultzca** [comment]
Please provide an example of the complete table definition for such as case.
