### ISSUE TITLE
Editor - Allow Custom Ordering of BitwiseSwitches

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#128]
Currently, it appears that the editor loads the bitwise switches based off bit order (0->X), irrespective of actual bit ordering. Given how Nissan has the DTC bits stored in a single block (alongside the fact that various flags are typically grouped together), it would be beneficial to have it be based off the position of the bits in the definition file, rather than the position on the bits in the actual bit order. Technically, an attribute could be added to signify whether the bitwise switch should be loaded based off definition order or based off bit position. 

ex. `		<bit position ="1" name="P0031 - AFR Sensor Circuit Low (B1 S1)"/>
		<bit position ="0" name="P0032 - AFR Sensor Circuit High (B1 S1)"/>`

Currently, even though bit pos 1 is listed before bit pos 0, RR would have the bitwise switch window start at bit pos 0. Changing this to being based off position in the definition file would allow for the window to start at bit pos 1.

**Comment by GTO2013** [comment]
I fixed this in #166, the BitwiseSwitch will take the order from the definition file now. If you want to order it by bit you just have to order it in the definition
