### ISSUE TITLE
Editor - 1D Table has Awkward Operation

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#132]
In a recent update, 1D tables were made usable for single value tables. While they work well, the scaling units operate funky. For one, it only uses the scaling provided and doesn't allow you to show the raw scaling. On top of this, when using multiple scaling types, you have to click off then click back onto the value in order to get it to update to the new scaling. Sometimes, it just doesn't change the scaling at all. 

If 1D tables still aren't meant to be used, then obviously it's not much of a concern. But I saw in one of the recent updates that a fix was added so I thought I'd test it out and give an update!

**Comment by GTO2013** [comment]
This is for a build of the github master, not for the official version off the website correct? I am currently fixing some things regarding labels in #131. Maybe we can add a pre-release tag for things like this @dschultzca?

**Comment by Pytrex** [comment]
Yup! A tag would definitely be appreciated, as there will always be pre-release issues that aren’t found in the past official release haha

**Comment by Pytrex** [comment]
Turns out that when I originally made this issue, I didn't have the most up to date version. Because now that I'm on the most recent one, everything is functioning as intended. I'll close the issue for now since everything functions properly from what it appears, but feel free to reopen it if anything arises! :)
