### ISSUE TITLE
Beta Editor - Multiple Checksums Requires Proper Ordering

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#134]
So when using multiple checksums, you need to order them properly if the checksum value itself resides in the range of the other checksum. For example, the alt checksum values located at 0x240C and 0x2410 are within the std checksum's range. With the checksums ordered in the following way, the std checksum gets calculated before the alt checksum does, resulting in a checksum error being thrown due to the std checksum now being incorrect since it was calculated without the new alt values. Saving again will fix said issue, but it wouldn't be apparent until you tried reloading the ROM. 
`<checksum type="std" start="0x0000" end="0xFFFFF" sumloc="0x8C38" xorloc="0x8C30"/>	
<checksum type="alt" start="0x2414" end="0x4162" sumloc="0x240C" xorloc="0x2410"/>`

Ordering the checksums with the alt before the std checksum results in proper checksum operation, as the alt checksum gets updated before the std checksum does. 
`<checksum type="alt" start="0x2414" end="0x4162" sumloc="0x240C" xorloc="0x2410"/>
<checksum type="std" start="0x0000" end="0xFFFFF" sumloc="0x8C38" xorloc="0x8C30"/>`

Is this something that's so minorly used that it's better just to remember that the std checksum must come last?

**Comment by dschultzca** [comment]
Are you saying that the Editor is changing the order in which the checksums are calculated compared to how they are ordered in the definition?
Or are you suggesting that if a user defines an incorrect order in the definition that a checksum calc error occurs?
Should we add an 'order' attribute which defines the order of calculation to help protect the user from themselves?
(These last two questions require the user to know how the ECU code works when they create/modify a definition).

**Comment by Pytrex** [comment]
If the user defines the order incorrectly in the definition file, then the checksum calc error occurs. The editor seems to just calculate from top down. But honestly, it would just depend on whether people utilize the multiple scalings or not. If multiple checksums are typically reserved for those who have extensive knowledge of the innerworkings of the ECU, then it would probably be safe to just leave it how it is, with some sort of documentation somewhere explaining that the order DOES matter. Just wanted to make sure that you guys were aware of this, as it would be quite unfortunate for someone to brick their ECU over misunderstanding how the multiple checksum system works lol

> What is 'Beta Editor' in the title? If this is not an issue with the official release code, maybe you can quote the last commit hash you are testing against.

Good idea, I'll have to remember that for next time!

**Comment by dschultzca** [comment]
So this is user related.  If a user does not understand the inner workings of the ECU then they don't have the knowledge to create a definition.
It has already been documented (in the forums somewhere, or the Nissan wiki) how the checksums are calc's and their order.
I'll close this as it is not an application issue.
