### ISSUE TITLE
Editor - Table Base Error for Switches or Fixed Axes

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#140]
For GitHub https://github.com/RomRaider/RomRaider/commit/49f5f57459c2e7ae740377187c1614f61f6851b2

So when attempting to use table bases for tables with fixed axes or for switches, it throws a `XML Parse Exception: Table type unspecified for name="(Insert Table Name here)"` It seems that tables with active axes operate just fine, as well as 1D values. So 3D maps and 2D tables work fine with active axes, but both throw the error if they have fixed axes. The switches error is probably caused by the same thing, since the values are basically fixed values.

**Comment by dschultzca** [comment]
You are referring to tables with an axis definition of `<table type="Static Y Axis"` ?
Please provide a sample definition if not.

**Comment by Pytrex** [comment]
Ooh. So when using "Static Y Axis" rather than just "X/Y Axis", it does still throw the same error. However, it at least loads the table properly this time. 

		<table type="Static Y Axis" name="MAF Sensor (V)" sizey="64">
		.........
		</table>
		<description>mQTBL- Inhalation air quantity conversion table. This table represents airflow through the MAF sensor at a given voltage. For stock MAF diameter intakes, I'd strongly recommend utilizing the MAF Factor alongside Fuel Compensation to dial in your fueling, rather than utilizing this table.</description>
	</table>
	
	<table base="MAF Table 1" name="MAF Table 2" category="Map Switching//Map Set 2"/>

**Comment by dschultzca** [comment]
I think you need to provide the entire table definition.

**Comment by Pytrex** [comment]
<table type="2D" name="MAF Table 1" category="Map Switching//Map Set 1" storagetype="uint16" sizey="64" userlevel="1">
		<scaling base="Standard Mass Airflow (x*1.05)/256" format="0.00"/>
		<table type="Static Y Axis" name="MAF Sensor (V)" sizey="64">
			<data>0.00</data>
			<data>0.08</data>
			<data>0.16</data>
			<data>0.24</data>
			<data>0.32</data>
			<data>0.40</data>
			<data>0.48</data>
			<data>0.56</data>
			<data>0.64</data>
			<data>0.72</data>
			<data>0.80</data>
			<data>0.88</data>
			<data>0.96</data>
			<data>1.04</data>
			<data>1.12</data>
			<data>1.20</data>
			<data>1.28</data>
			<data>1.36</data>
			<data>1.44</data>
			<data>1.52</data>
			<data>1.60</data>
			<data>1.68</data>
			<data>1.76</data>
			<data>1.84</data>
			<data>1.92</data>
			<data>2.00</data>
			<data>2.08</data>
			<data>2.16</data>
			<data>2.24</data>
			<data>2.32</data>
			<data>2.40</data>
			<data>2.48</data>
			<data>2.56</data>
			<data>2.64</data>
			<data>2.72</data>
			<data>2.80</data>
			<data>2.88</data>
			<data>2.96</data>
			<data>3.04</data>
			<data>3.12</data>
			<data>3.20</data>
			<data>3.28</data>
			<data>3.36</data>
			<data>3.44</data>
			<data>3.52</data>
			<data>3.60</data>
			<data>3.68</data>
			<data>3.76</data>
			<data>3.84</data>
			<data>3.92</data>
			<data>4.00</data>
			<data>4.08</data>
			<data>4.16</data>
			<data>4.24</data>
			<data>4.32</data>
			<data>4.40</data>
			<data>4.48</data>
			<data>4.56</data>
			<data>4.64</data>
			<data>4.72</data>
			<data>4.80</data>
			<data>4.88</data>
			<data>4.96</data>			
			<data>5.04</data>
		</table>
		<description>mQTBL- Inhalation air quantity conversion table. This table represents airflow through the MAF sensor at a given voltage. For stock MAF diameter intakes, I'd strongly recommend utilizing the MAF Factor alongside Fuel Compensation to dial in your fueling, rather than utilizing this table.</description>
	</table>
	
	<table base="MAF Table 1" name="MAF Table 2" category="Map Switching//Map Set 2"/>

Here ya go! Also, is "Static Y Axis" the preferred default for static 2D tables?

**Comment by dschultzca** [comment]
> Here ya go! Also, is "Static Y Axis" the preferred default for static 2D tables?

Static Y Axis or Static X Axis
