### ISSUE TITLE
Logger - MAF tab can't find table

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#150]
https://www.romraider.com/forum/viewtopic.php?f=5&t=18991

Add a properties file so a user can change the table name the MAF tab is looking for (like the LTV properties file).
Is there a way to call the Editor so I does need to be open first?

**Comment by GTO2013** [comment]
Isnt it possible to use the logparam=PXX property from the editor definition thats already used from the logger?

**Comment by dschultzca** [comment]
This is the other way round, the Logger is looking for the table definition of the ROM to be able to update the table with new values that it interpolated from recorded data.

**Comment by dschultzca** [comment]
Nothing to fix here as there should only be one instance of the table name in the definition.
