### ISSUE TITLE
Editor - Switch Table allows both options to be selected

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#174]
Switch table such as DTC should only allow one entry to be selected.  On and Off at the same time is not a valid option.
Radio buttons on these tables are the best choice.  

![image](https://user-images.githubusercontent.com/1688870/163055869-4104346a-ea63-4eea-a427-c6af6d14db4b.png)

**Comment by GTO2013** [comment]
Hi,
there are cases where multiple choices can be selected, for the Bitwise Switch for example. What is the on and off state for this switch? It should automatically disable the checkbox where the data doesn't match the state

**Comment by dschultzca** [comment]
In this case and in most other cases where is Switch Table is used and it is not a bitwise group or mask, there should only ever be one selectable option, such as a radio button group.  Here a DTC can not be set both On and Off at the same time.  
Using a checkbox has to be managed to ensure that only one option is selectable and other automatically unselected.  This had been the case for many years, I'm not sure when the behaviour changed, I didn't catch it when it did.  
We should be using radio buttons for Switch tables and check boxes for bitwise/masks.
