### ISSUE TITLE
Editor - Various Potential Issues with BitwiseSwitches

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#186]
Unless there have been changes to how we're supposed to format bitwise switches in the definition file, it seems like there are a few issues with the new bitwise switch stuff. All of this is from v0.9.2 by the way!

Potential Issues:
1. BitwiseSwitches appear as "switch" data types inside RomRaider (BitwiseSwitches and Switches still operate the same as they used to, but both show up as "switch" data types in Table Properties)
2. Regular switches have check boxes rather than radio buttons (might be intentional, but radio buttons make more sense for switches than check boxes)
3. While 8-bit bitwise switches work fine, anything over 8-bit (sizey > 1) results in RomRaider displaying the wrong bits as being enabled, alongside having the weird operation seen below.
![Animation](https://user-images.githubusercontent.com/13327710/167435664-0431c088-7faa-42af-8eff-02d88787fdaa.gif)

Not an issue on its own, but might be worth discussing. It seems that all category folders and tables are being sorted by alphabetical order rather than by ordering in the definition file. Due to this, any numbers over 2 digits won't display in the expected order. 
![Flags ordering](https://user-images.githubusercontent.com/13327710/167453194-811c4ccc-092e-40a3-8772-4480be1f4e5f.png)

**Comment by dschultzca** [comment]
Do you need to define storagetype="x" greater than unit8 for these 16 or 32 bit options?  To me that better describes the data being manipulated, sizey="1" with storagetype="uint32".  
Other options:
sizey="1" with storagetype="uint8"  
sizey="1" with storagetype="uint16"

**Comment by Pytrex** [comment]
> Do you need to define storagetype="x" greater than unit8 for these 16 or 32 bit options? To me that better describes the data being manipulated, sizey="1" with storagetype="uint32". Other options: sizey="1" with storagetype="uint8" sizey="1" with storagetype="uint16"

That does seem to work! Good idea! And like you said, it makes more sense than specifying sizey when it can be covered by the storagetype. 

The only issue with that now is being able to specify bitwise switches larger than four bytes. Not sure if the Subaru defs utilize anything like this, but I have all the DTC's stored in a single bitwise switch which is 71 bytes long. So in v0.9.2, there's no way to have it setup like this without sizey being able to be greater than 1. But there are other OEM supmasks ("DOMON Distinction Flags" is 8-bytes) that are larger than uint32, so it's not just DTC's haha

**Comment by dschultzca** [comment]
What you are creating is a table of bitfield items encoded as bytes.  There's no support in RomRaider for a storagetype greater than 32 bits in length.  Even Java is limited to a Long which is 64 bits, but we have no Long support as a table data type in RomRaider.  Even the SH processor is limited to 32 bits at a time.  If it is evaluating more that 32bits it will be doing so with two or more registers so it is not really a true 8-byte mask.  
If at all possible, I'd mimic the way the ECU code handles these bitfields.  Most likely it is evaluating them a byte at a time.

**Comment by a33b** [comment]
While the processor evaluates a byte (actually a bit) at a time, the definitions are often stored as 32 bit fields which matches OBD-2 bit supported supmasks. It reduces the amount of definitions to be created significantly to leave these as 32 bit fields.

**Comment by dschultzca** [comment]
Is this working after updating the table attributes, can this issue be closed?

**Comment by Pytrex** [comment]
> Is this working after updating the table attributes, can this issue be closed?

While it's upsetting to lose the ability to store all ~568 DTCs in one bitwise switch rather than in numerous separate ones, it's true that the ECU itself doesn't handle it that way. So I can't be too upset about it, really :P 

But yup! Using sizey="1" with uint16/32 storagetypes will follow how the ECU handles it perfectly.
