### ISSUE TITLE
Editor - Graphical Issues with Pop up Windows

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#188]
This is from the current build 6573eda, but it seems like I can replicate this issue on v0.8.2 as well. 

So it seems that after you select a map from the comparison window and move the map around, it causes all pop up windows to have these graphical issues until you restart RomRaider. When you don't move any of the maps around, it doesn't result in any problems.

Also, the image that glitches onto the pop up window is dependent on whether the pop up window was over the main RomRaider Editor window. So if the pop up window is above a map and you click on the map, it sometimes will show a glitchy map on the pop up window when you click on the pop up window again.

[rr_system.txt](https://github.com/RomRaider/RomRaider/files/8693940/rr_system.txt)
![PGIssue](https://user-images.githubusercontent.com/13327710/168448781-79102d0f-5b59-4a6a-83d5-5f04451d221f.png)
![PGIssue2](https://user-images.githubusercontent.com/13327710/168448783-5306a4c5-60ae-43f6-9dcd-d546332815b8.png)

**Comment by dschultzca** [comment]
This is no build with that commit signature.  The last build was e6c678897b0c, version 0.9.2.  
I'm unable to replicate the problem you see.  I've tried with Java 1.6 and 1.8.

![image](https://user-images.githubusercontent.com/1688870/168452591-a0760b37-e243-4360-b4db-61a0e2be5e01.png)

**Comment by Pytrex** [comment]
Just so it's made public, I think it's something to do with my main monitor. Dragging the RR window to either of my two other monitors results in completely normal operation. So I think it's definitively a monitor related issue and not RR related. But thanks for checking! :)
