### ISSUE TITLE
Editor - v0.9.3 - Various tables displaying erroneous columns and values

### ISSUE THREAD

**Issue by singularity888** [RomRaider/RomRaider#192]
**Describe the bug**
- Using v0.9.3 and JDK 8u331, observed that CL/OL delay tables have more editable values not seen previously, as well as the MAF scaling tables now have extra columns and values (54 vs 48) compared to previous RR versions used - did not observe this behavior on RR  v0.8.2 / JDK 8u321.
-Definitions used: 0.8.3.1b (unchanged since using last version)

**To Reproduce**
Installed latest version, loaded stock ROM (A8DH201X). 

**Expected behavior**
Expected to see same number of columns/rows in various tables, as seen in previous versions (Did not update definitions).

**Screenshots**
Screenshot of editor with stock/unmodified rom loaded into it is attached for clarity (A8DH201X)
![v093_tables](https://user-images.githubusercontent.com/105962158/169639969-fd3d4b99-d788-4d34-94da-818561e2e76d.PNG)

**Desktop (please complete the following information):**
 - OS version: Win10 21H2, 19044.1706
 - Java version: 1.8.0_331-b25 (x86)  (JDK 8u-331)
 - RomRaider version: 0.9.3 MAY20 2022 

**Additional context**
Unsure what other tables or ROMs are affected, if any. Uninstalled latest version, reinstalled 0.8.2 (kept Java 8u331) and issue went away. Reinstalled v093 and issue returned. <=Did this to confirm that software change caused this behavior, not an error in editing maps/values or while saving. Unsure / did not test if RR versions between the two I have been using experience same issue.

**Comment by dschultzca** [comment]
What definition file are you using exactly, can you provide a link?

**Comment by dschultzca** [comment]
After a quick look, it appears the Editor is not updating the sizey value after inheriting the BASE definition tables attributes.  In the case of MAF.  The BASE has a sizey of 54 and the ROM specific value for this table modified the sizey to 48.
```
 <rom base="A8DH200X">
  <romid>
   <xmlid>A8DH201X</xmlid>
```

```
 <rom base="32BITBASE">
  <romid>
   <xmlid>A8DH200X</xmlid>
  <table name="MAF Sensor Scaling" storageaddress="0xCED60" sizey="48">
   <table type="Y Axis" storageaddress="0xCECA0" />
  </table>

```

```
 <rom>
  <romid>
   <xmlid>32BITBASE</xmlid>
  <table type="2D" name="MAF Sensor Scaling" category="Mass Airflow / Engine Load" storagetype="float" endian="little" sizey="54" userlevel="2" logparam="P12">
   <scaling units="Mass Airflow (g/s)" expression="x" to_byte="x" format="0.00" fineincrement=".1" coarseincrement="1" />
   <table type="Y Axis" name="MAF sensor" storagetype="float" endian="little" logparam="P18">
    <scaling units="volts" expression="x" to_byte="x" format="0.00" fineincrement=".01" coarseincrement=".1" />
   </table>
   <description>This is the scaling for the mass airflow sensor.</description>
  </table>
```
