### ISSUE TITLE
Valid Definition file considered incorrect

### ISSUE THREAD

**Issue by GTO2013** [RomRaider/RomRaider#196]
Hi,
with the current version of 9.4 I cannot add the following definition to the definition manager anymore:
[KMB_E36.C25.zip](https://github.com/RomRaider/RomRaider/files/9226155/KMB_E36.C25.zip)

I havent been checking the project recently, which checks are done to validate a definition file now?

**Comment by dschultzca** [comment]
Definitions are checked for some common strings to ensure the user is not trying to load a Logger, dyno, EcuFlash, etc. definition file.  When loading an Editor definition file the contents is checked against strings that can be found in the  `RomRaider\customize\nameSequences.properties` file.  If a string sequence is found you will get an error message indicating the suspected file type as the **first** word of the message.  

In your case I suspect it is triggered by line 48 where an invalid scaling attribute is present.  The `name` attribute is only valid in the scalingbase element.  If you wish to provide scaling elements with different units of measure then the `category` attribute should be used.  Remove the `name` attribute or change it to `category` to load your definition.  

Ref commit 16dbe71

**Comment by GTO2013** [comment]
Correct, the name attribute was the problem. Thanks 👍
