### ISSUE TITLE
[Logger]Initiailizing logger ...  

### ISSUE THREAD

**Issue by taneman** [RomRaider/RomRaider#213]
**Screenshots**
![image](https://user-images.githubusercontent.com/130019996/230257542-0c00eb6b-9cc6-4f4a-9fc0-9239c528c47f.png)

**Desktop (please complete the following information):**
 - OS version: Win10
 - Java version: Version 8 update 351
 - RomRaider version: 0.9.4 MAY23 

**Additional context**
Whenever I try to open the logger, it won't open it no matter how long I've waited. It's just freezing there forever pls help!!!

**Comment by taneman** [comment]
![image](https://user-images.githubusercontent.com/130019996/230258420-fc0e3a51-1bc5-475b-93d1-1d010d34bfee.png)

**Comment by dschultzca** [comment]
Try deleting your settings.xml file.  If you had a crash or terminated RomRaider abnormally it could have become corrupt.  
<user_home_dir>\.RomRaider\settings.xml
Then start RR and add in your defs in the Editor and Logger.
