### ISSUE TITLE
Logger - Failure to initialize SSM/Openport 1.3

### ISSUE THREAD

**Issue by jevolk** [RomRaider/RomRaider#217]
Logger reports:

> Unable to send ECU init - check cable is connected and ignition is on

- Openport 1.3 cable
- SSM K-Line (ECU is pre-canbus) protocol
- FTDI driver 2.12.14.0 (4800 8/n/1)
- Windows 11
- JavaSE-17 (jdk-17) (eclipse)
- RomRaider 0.9.4-MAY23-2022
- Able to pull ROM with EcuFlash
- **Able to log using FreeSSM**

RomRaider writes init sequence `80 10 f0 01 bf 40` and then the next read is the same 6 bytes repeated back. That is the only data ever available for reading. The expected behavior is demonstrated on this system by FreeSSM: it writes the same sequence and then reads the same 6 bytes but then moves on to reading a further 15 bytes `80 f0 10 39 ff a2 10 11 43 12 58 40 06 f3 fa`.

The problem is probably with jSerialComm. Any ideas?

**Comment by dschultzca** [comment]
It may very well be jSerialComm.   [Others have reported a problem](https://www.romraider.com/forum/viewtopic.php?f=5&t=20611) using Openport 1.3 cables, while generic VAG-COM cables with FTDI chips work fine.

Are you able to provide more details such as a screenshot of the OpenPort cable description after you query it with [FT_Prog](https://ftdichip.com/utilities/#ft_prog)?

**Comment by jevolk** [comment]
Dale, thanks for continuing to maintain this project. I made significant headway in the last few hours here with the following hack:

https://github.com/RomRaider/RomRaider/blob/8d1939f4ba34ac5db268d077cef347e317ffcf54/src/main/java/com/romraider/io/serial/connection/SerialConnectionImpl.java#L71

Prior to the write I added `serialPort.setRTS()` and after the flush I added `serialPort.clearRTS()`. The logger is able to connect and operate! Unfortunately after a few seconds it fails with something like "invalid header: expected 80 got 00" and struggles to reconnect. I reduced the FTDI driver buffers from 4096 to 512 in windows settings and the connection last a few minutes rather than seconds. 

Thanks for letting me know about FT_prog, I will give it a try. I suspect the tactrix 1.3 device has expectations for RTS/DTR assertions which aren't being negotiated by the new jSerialComm glue. Please read the tea leafs here as much as you can.

**Comment by dschultzca** [comment]
The Openport 1.3 does indeed use RTS (_and DTR for L-line_).  We assert RTS here (and check for an error) to enable K-line transmit and receive.  It should not be cleared after the connection is established.
https://github.com/RomRaider/RomRaider/blob/8d1939f4ba34ac5db268d077cef347e317ffcf54/src/main/java/com/romraider/io/serial/connection/SerialConnectionImpl.java#L207
Maybe something else in jSerialComm is clearing it.

**Comment by dschultzca** [comment]
You could also try a more recent release of [jSerialComm](https://github.com/Fazecast/jSerialComm/releases). The notes indicate some changes to RTS activation.

**Comment by dschultzca** [comment]
Looking back to when we used RXTXcomm, the RTS state on port open was false `serialPort.setRTS(false);`  
Maybe line 207 should actually be `if (!serialPort.clearRTS())`.  
Can you try that can let me know?

**Comment by jevolk** [comment]
FTR:
![Screenshot 2023-10-07 202210](https://github.com/RomRaider/RomRaider/assets/4682706/82d35d39-a89a-42b6-8d6c-f2a45ffe2c46)
![Screenshot 2023-10-07 202417](https://github.com/RomRaider/RomRaider/assets/4682706/f7ce1901-c82d-424e-86d0-5332fee7bb7c)
