### ISSUE TITLE
[Editor] Scaling Name - "name" or "category"?

### ISSUE THREAD

**Issue by GTO2013** [RomRaider/RomRaider#218]
I am a bit confused about how to define different scalings for a table. I thought this was correct, which is from a Subaru definition (ecu_defs_multi.xml) you sent me once:
```
    <scaling name="Metric" units="Degrees C" expression="x" to_byte="x" format="#" fineincrement="1" coarseincrement="5" />
    <scaling name="Standard" units="Degrees F" expression="(x*1.8)+32" to_byte="(x-32)/1.8" format="#" fineincrement="1" coarseincrement="5" />
```
However this does not work, it only works if name is replaced by category. Was this changed at some point? I have found a few definitions which did not load because of this. What do you think about making both name and category valid properties?

**Comment by dschultzca** [comment]
That is an old definition and not compatible with the current version of RR.  When multiple scaling options were introduced the attribute name was reused.  That is in conflict with the scalingbase element and how you reference it using the name attribute.  
see issue: https://github.com/RomRaider/RomRaider/issues/137  
https://www.romraider.com/index.php/RomRaider/EditorXMLReferenceGuide

**Comment by dschultzca** [comment]
I guess we could implement a check when loading the definition. If no `scalingbase` elements are present then use the name attribute to populate the category field and continue to load.

**Comment by dschultzca** [comment]
> Some definitions are fairly large and search and replace does not always work, unless you come up with a regex. I know people who have switched from 0.5.9 to newer versions tried the latest versions and could not use their old definitions, so they went back to 0.5.9.

What exactly is making those definitions incompatible with the latest version of the Editor.  I have no problem using a definition created in 2010 to view a ROM.  Even our base [Subaru definition load](https://www.romraider.com/forum/topic360.html) from about the same era works.  

I would only expect there to be a conflict if a definition has multiple scaling elements for a table and used the name attribute to categorize them.  This is an easy search/replace fix to make those work.  I'm not aware of many definitions that use this feature.  The MS41 ECU Definitions in it's current state seem to work fine too.

**Comment by GTO2013** [comment]
I remember people sending me RomRaider definitions from https://www.ms4x.net/index.php?title=Definition_Files#RomRaider that didnt work.
But some guy called Dschultz pushed a fix this year, so I guess thats why it has gotten less :)
Its not possible to add the definition to the definition manager, because it assumes its an EcuFlashBase file (<scaling name). I was about to write a workaround for this, but I didnt understand why actually.
I then found a bug: There is a space in the .properties file and it doesnt actually find the <roms> tag. I feel like adding things to the definition manager is faster now aswell.
I looked into making "name" backwards compatible, but it felt quite messy. The upper part felt more important to fix for me.

**Comment by dschultzca** [comment]
Any trailing space in the value of a key in the properties file is to be considered, this is to ensure an exact match of that item (_other properties files share this same feature, such as table names which can end with a space_).
If the fix is to remove the trailing space, then it should be applied to the properties file value and not a wholesale change to eliminate a trailing spaces in code.  Can you resubmit your change?

**Comment by GTO2013** [comment]
Sure, check my PR
