### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by GTO2013** [RomRaider/RomRaider#225]
Hi,
the last public release is already quite long ago. Since then a few features and bugfixes have been added. I think a new release would be nice if you can find the time for it.

Cheers,
Robin

**Comment by dschultzca** [comment]
Sure, I was going to ask if you were ready after the code updates.

**Comment by GTO2013** [comment]
Sure, I would call Dataflow Simulation experimental in the Release Notes, but it should be working. I will see if it's a feature that is used by the community first before I put more work into it

**Comment by GTO2013** [comment]
Actually, nevermind. I found a bug :) I will create a PR to fix it.

**Comment by GTO2013** [comment]
Thanks for the new Release 👍
