### ISSUE TITLE
[Logger] VANOS parameters not queried for BMW/MS42 using v370 logger definitions 

### ISSUE THREAD

**Issue by dgktkr** [RomRaider/RomRaider#230]
VANOS parameters show up and can be selected on the left side of the Logger screen, but the values plotted on the right side are constant (0) and implausible.The values should be ~100 and ~-100 for intake and exhaust.

Windows 11, Oracle Java 1.8.0_401-b10(x86), RomRaider 1.0.0, Logger def 370

With one line (|| groupTest.startswith("0x0b0x90") added below 174 in src/main/java/com/romraider/logger/ecu/comms/io/connection/DS2LoggerConnection.java and a rebuild, the problem is solved on my computer.

**Comment by dgktkr** [comment]
VANOS parameters show up and can be selected on the left side of the Logger screen, but the values plotted on the right side are constant (0) and implausible.The values should be ~100 and ~-100 for intake and exhaust.

Windows 11, Oracle Java 1.8.0_401-b10(x86), RomRaider 1.0.0, Logger def 370

With one line (|| groupTest.startswith("0x0b0x90") added below 174 in src/main/java/com/romraider/logger/ecu/comms/io/connection/DS2LoggerConnection.java and a rebuild, the problem is solved on my computer.

**Comment by dschultzca** [comment]
Fixed by commit e7e8a9f01014b27cce24e0956b493a48ca271a7e
