### ISSUE TITLE
Logger configuration/opening exception - System can't find specified file

### ISSUE THREAD

**Issue by paulo-jgf** [RomRaider/RomRaider#233]
**Describe the bug**
When I try to open the logger this exception occurs. File name and extension is wrong in the exception messenge, but the directory is stated right.

**To Reproduce**
1. Launch logger from app or from it's exe.
2. Add any definition file.

**Screenshots**
![image](https://github.com/RomRaider/RomRaider/assets/40891723/2b1022cd-44d9-4be0-80a6-df3114694252)

Translation: "System can't find the specified file"

**Desktop (please complete the following information):**
 - Windows 10 22H2
 - Java versions: 
   1.8.0_333-b02 (x86) ; 1.8.0_411-b09 (x86)
 - RomRaider versions: 
    0.9.4MAY232022 ; 1.0.0DEC012023

**Additional context**
I tried updating RomRaider and JRE, but no joy. The logger definitions I am trying to load is the Subaru definitions xml file. Please let me know what other evidence I should provide, because I think this problem is related to my system.
Thanks in advance.

**Comment by dschultzca** [comment]
The error is correct.  You are trying to load the .dtd file as if it were a Logger definition file.  The latest Logger definition file (XML) is here: https://www.romraider.com/forum/viewtopic.php?p=66788#p66788

**Comment by paulo-jgf** [comment]
Thank you dschultz, the definitions you pointed me too worked. I was using the definitions provided on Merp's github, which are already at .XML format, but it seems compatibility is lost with recent romraider releases.

**Comment by dschultzca** [comment]
For some older definitions you may need the logger.dtd, but it is not a file you choose to use, just save it in the same directory as the Logger definition XML file.  
The latest definitions don't need this file, it is not related to RomRaider versions, but a definition file format issue.

The error above is 'file not found', so most likely it was moved and therefore not found.  You have two different directories in your comments above: `C:\Users\paulo\Desktop\REMAP\` and `C:\Users\paulo\Desktop\REMAP\Subaru\`

**Comment by paulo-jgf** [comment]
Oh, now I understand, thank you for taking the time to explain me. 

About the path/files sorry for the confusion. I tried it at two different paths, but I never unpacked the .dtd, so the problem is exactly what you described. Old definitions requires it, and it wasn't there.
