### ISSUE TITLE
Logger - Gauge min/max/step limits incomplete

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#5]
Some Gauge min/max/step limits are not defined in the logger.xml. These values are used to set the Gauge minimum, maximum and the major tick mark division labels on the Dashboard.  If not set the Gauge may show values higher or lower than the default labels selected.  This does not affect logging to a file as this values do not place any restrictions on values read and written.

**Comment by GTO2013** [comment]
Isn't this issue more a user error than an actual RR problem? Adding the correct min/max values in the logger.xml fixes this, correct?

**Comment by dschultzca** [comment]
This is a definition deficiency and not an application issue.  Therefore closing.
