### ISSUE TITLE
Logger - Add Throttle Volts to Dyno Tab

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#50]
For cars without a Throttle Angle parameter use Throttle Volts instead.
Add a user field so they can set their desired Throttle Angle or Volts threshold to indicate when at WOT.

**Comment by GTO2013** [comment]
Once you select VDC you will get a popup telling you its not supported

**Comment by dschultzca** [comment]
Depending on the ECU, if volts DC is a parameter then you can use it.  Let us know how it goes, then we can close this.

**Comment by grafitto** [comment]
I am relatively new to this (tuning), just ordered Tactrix cable, I am sure it will take some time to reach my country so that I can test. In the meantime any suggestions for good first issue? @dschultzca

**Comment by dschultzca** [comment]
This repository is for software issues related to the RomRaider Editor/Logger.  If you have tuning questions please visit the RomRaider forums.

**Comment by grafitto** [comment]
@dschultzca I want to start contributing on development of RomRaider Editor/Logger. So I meant a good first github issue I can work on

**Comment by GTO2013** [comment]
I think a GUI to edit definitions and add tables would be the most needed addition to the Editor at least. Thats not really an easy first task though

**Comment by grafitto** [comment]
Submitted a PR on the issue https://github.com/RomRaider/RomRaider/pull/198
