### ISSUE TITLE
Compare Images - Color Blindness

### ISSUE THREAD

**Issue by Swivelgames** [RomRaider/RomRaider#74]
We may be a minority, but I was a bit perplexed as to how to use the Compare Images functionality until I stumbled upon an explanation in a video tutorial I was watching.

Apparently, the changes are denoted to the user via color coding (red=changes, green=no changes). This is awesome, unless you're color blind... Unfortunately, they look the same to me!

Is it possible to add some other type of visual cue or contrast the colors more to illustrate the changes?

A couple of suggestions:
- Prepend the table name with `[CHANGED]`
- Hide all tables that are the same and only show tables that are different
- Bold table names that are different and italicize table names that are the same
- Grey-out tables that are the same, and make tables that are different black (#000)

Colors are awesome, and I can definitely see the gradients and understand the visual cues in most of the areas of this application. But comparing Red and Green is almost always a difficulty with individuals who are impaired with color blindness, especially when the colors are applied to things that are thin (like text). A red versus green line are much more difficult to distinguish than a red versus green square.

Also, if there's a specific one of these suggestions that's liked the most, I can certainly contribute and pull request if you can point me in the general direction.

**Comment by scotthew** [comment]
@Swivelgames You can find the code for the compare coloring in the CompareImagesForm here...

https://github.com/RomRaider/RomRaider/blob/master/src/main/java/com/romraider/swing/CompareImagesForm.java

It would be easy to add they various styling changes for color blind users.  My suggestion would be to use whatever technique works best for you.

I originally added this functionality a while back to help me compare changes between stock vs modified ROMs and across revisions of my own ROMs.

**Comment by Swivelgames** [comment]
That's exactly what I use was hoping to see this for. The functionality works great, but if you're open to me adding some other visual cues for us with crappy eyes, that'd be awesome! 😃 

I'll try and throw up a PR sometime soon if possible.

**Comment by scotthew** [comment]
Yes.  Feel free to make any changes that you want.  Also consider adding any sort of help or descriptions to the compare image functionality to help other users understand what this tool is/can be used for.

I have also considered moving the "save as repository" functionality into this compare tool.  Save as repository takes the map and saves it to flat files.  In my tuning process I save as a repository and add the text files as a git repository.  I use the Git repo for ROM revision tracking purposes.  This gives a clear history of the ROM changes from a source control perspective and makes it easy to use dif tools to find out what changed.

**Comment by Swivelgames** [comment]
Oh very nice. I was curious what the `Save as Repository` was for.

If I have some time this evening, I'll see about adding more descriptive text to that dialog. Good idea!

As for `Save as Repository`, I'll brainstorm some ideas on maybe moving that into the dialog too and explaining it a bit as well.

**Comment by GTO2013** [comment]
This is already implemented in #75, so this can be closed too right?
