### ISSUE TITLE
DTD definition seems outdated

### ISSUE THREAD

**Issue by guicho271828** [RomRaider/RomRaider#86]
I was trying to write a converter from ecuflash xml file to romraider xml file, and found the dtd definition hugely outdated. There are no `tables`, `table2d` `table3d` tags at all in the current ecu_defs.xml .

**Comment by dschultzca** [comment]
The ECU definitions have evolved quote a bit since that DTD was created in 2006 (but never updated).  Your best bet is to review the unmarshalling code: https://github.com/RomRaider/RomRaider/blob/master/src/main/java/com/romraider/xml/DOMRomUnmarshaller.java

**Comment by ortang** [comment]
What is this for

**Comment by guicho271828** [comment]
BTW this is the converter
https://gist.github.com/guicho271828/dbb4195df9316fd37e333eb9b828fde3

**Comment by guicho271828** [comment]
@ortang  Are you asking for my motivation?
I have a 07 NC Miata and recently bought an OFT, but could not find a good xml definition for it.
I found these xml files for EcuFlash https://github.com/speepsio/romdrop/tree/master/metadata but EcuFlash (windows) was not my option because as a software R&D I am heavily inclined to Linux, even though it worked on Wine.
