### ISSUE TITLE
Impossible to start RomRaider - check if runnning port conflict on Windows Vista and later when Hyper-V enabled(potentially also in other cases)

### ISSUE THREAD

**Issue by duverre** [RomRaider/RomRaider#88]
Description:
The "if running"check can fail even in cases when there is no service explicitly listening on port 50001 because of the way Windows services sometimes reserve ports for use. This makes it impossible to start RomRaider.

References:
1. [Unable to bind ports: Docker-for-Windows & Hyper-V excluding but not using important port ranges](https://github.com/docker/for-win/issues/3171)
2. [The default dynamic port range for TCP/IP has changed since Windows Vista and in Windows Server 2008](https://support.microsoft.com/en-us/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista)

Clarification:
The exclusion ranges seen in the first post of link 2 get randomised on every startup, but the way they are generated specifically by Hyper-V makes it almost certain that port 50001 is going to be in them. They can not be modified even with elevated privileges, because they are created by system services.

Workaround:
1. Disable Hyper-V
2. Add port 50001 manually as reserved port. Run the following from an elevated command prompt cmd: 
netsh int ipv4 add excludedportrange protocol=tcp startport=50001 numberofports=1
4. Reenable Hyper-V

Suggestions for (pseudo)permanent solution:

1. If "if running" check fails, decrement/increment port by a given value and check again. Repeat until an available port is found. I went through the code and didn't notice anything external to RomRaider relying on it listening on this port. If I have missed something...
2. An alternative would be to allow manual configuration of the port in some way.
3. Another alternative(this one is the pseudo-permanent) would be to change the hardcoded port to be outside of the range mentioned in link 2 from the references.

P.S. Many people seem to have been pestered by the port problem(due to different reasons) over the years from what I have seen on the internet while looking for a solution. I myself was forced to use a different OS in a dual-boot configuration for some months now(apparently since enabling Hyper-V). Now finally decided to engage the situation more deeply, because I could not take it anymore. I would be willing to contribute any of the above given suggestions in the form of code, if deemed adequate, in order to speed up the process.

**Comment by dschultzca** [comment]
Changed RomServer class TCP port in commit 07fef98d0beaa7c821fe9af6f29e5b19c6717964.

**Comment by duverre** [comment]
Issue still occurs with new port number. Port needs to be outside of the 49152-65535 range due to reference 2 from the first comment.

**Comment by dschultzca** [comment]
Solution #1 negates the purpose of opening a known port to detect that RomRaider is already running.
Solution #2 requires the use of an environment variable or command line parameter to select a port number prior to RomRaider execution.
Solution #3 is the current method; current code just needs to be modified to use a port outside the claimed range.

**Comment by dschultzca** [comment]
Changed RomServer class TCP port in commit 6865057dc725b8f23fe5cb26e7e81eb6aab60336
