### ISSUE TITLE
Install freezes on Ubuntu 19

### ISSUE THREAD

**Issue by RyanHope** [RomRaider/RomRaider#89]
The install does not progress beyond the screen where you select which components are installed when installing on ubuntu 19.

**Comment by dschultzca** [comment]
Which version of Java are you using?

**Comment by dschultzca** [comment]
For Ubuntu 18 you need to use Java 32 bit version, maybe the same for 19.
I installed these prerequisites.

```
sudo apt install libusb-1.0-0:i386
sudo vi /etc/group    #added your username to the dialout group under which the VAG-COM cable is assigned
sudo apt install openjdk-8-jre:i386
sudo update-alternatives --config java    #select the option for openjdk-8-jre:i386 as your default jre
java -jar RomRaider0.5.9RC3-linux.jar
```

**Comment by HarryCaveMan** [comment]
So I am having this issue with raspbian buster and will probably only be able to use `openjdk-8-jre:armhf`. I'd rather use openjdk if I can.

**Comment by dschultzca** [comment]
FYI, on ARM, RomRaider will fail to run using Java 11.  Set your install to Java 8 32bit.  
You will also need ARM specific libraries for RXTX and Phidgets (if you need this plug-in, otherwise disable it).

**Comment by HarryCaveMan** [comment]
I am using openjdk-8:armhf which seems to be the only non-SE java 8 available for raspbian.
